#!/usr/bin/env python3
"""Builds sprite.js from the Phosphor SVGs in regular/, fill/ and duotone/.

sprite.js injects one hidden <svg> of <symbol>s into the page so mockups can use
    <svg class="ic"><use href="#ph-wifi-high"/></svg>
over file:// (where fetching external SVG files is blocked). Symbol ids:
    ph-<name>            regular weight
    ph-<name>-fill       fill weight
    ph-<name>-duotone    duotone weight (two paths, the first at opacity .2)
Every path carries fill="currentColor" through the parent, so colour is CSS.
"""
import json
import pathlib
import re

here = pathlib.Path(__file__).parent
symbols = []
names = []
for sub in ("regular", "fill", "duotone"):
    for svg in sorted((here / sub).glob("*.svg")):
        body = svg.read_text()
        inner = re.search(r"<svg[^>]*>(.*)</svg>", body, re.S).group(1).strip()
        sid = "ph-" + svg.stem
        symbols.append(f'<symbol id="{sid}" viewBox="0 0 256 256">{inner}</symbol>')
        names.append(sid)

sprite = '<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">' + "".join(symbols) + "</svg>"
js = (
    "// Generated by build-sprite.py from phosphor-icons/core (MIT). Do not edit by hand.\n"
    "// Usage: <svg class=\"ic\"><use href=\"#ph-wifi-high\"/></svg>\n"
    "(function(){var s=" + json.dumps(sprite) + ";\n"
    "function inject(){var d=document.createElement('div');d.innerHTML=s;document.body.insertBefore(d.firstChild,document.body.firstChild);}\n"
    "if(document.body){inject();}else{document.addEventListener('DOMContentLoaded',inject);}\n"
    "window.PH_ICONS=" + json.dumps(names) + ";})();\n"
)
(here / "sprite.js").write_text(js)
print(f"{len(names)} symbols -> sprite.js ({len(js)//1024} KB)")
