#!/usr/bin/env node
// Parses desktop/design/presets/*.css into src/theme/presets.ts so the design
// stays the source of truth for the ten themes. Run: pnpm gen-presets
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const dir = resolve(here, "..", "design", "presets");
const out = resolve(here, "..", "src", "theme", "presets.ts");

const TOKENS = ["base", "mantle", "surface", "overlay", "text", "subtext", "muted", "accent", "accent-text", "ok", "warn", "error", "vpn", "wifi", "border", "selection"] as const;
const ORDER = ["dark", "light", "catppuccin-mocha", "catppuccin-latte", "gruvbox-dark", "nord", "tokyo-night", "rose-pine", "dracula", "one-dark"];

type Preset = { id: string; name: string; scheme: "dark" | "light"; tokens: Record<string, string> };
const presets: Preset[] = [];
for (const file of readdirSync(dir).filter((f) => f.endsWith(".css"))) {
  const id = file.replace(/\.css$/, "");
  const css = readFileSync(join(dir, file), "utf8");
  const name = (css.match(/^\/\*\s*(.+?)\s*$/m)?.[1] ?? id).trim().replace(/\s*\(default\)$/, "");
  const scheme = css.match(/scheme:\s*(dark|light)/)?.[1] === "light" ? "light" : "dark";
  const tokens: Record<string, string> = {};
  for (const t of TOKENS) {
    const m = css.match(new RegExp(`--${t}:\\s*(#[0-9a-fA-F]{6,8})`));
    if (!m) throw new Error(`${file}: missing --${t}`);
    tokens[t] = m[1]!.toLowerCase();
  }
  presets.push({ id, name, scheme, tokens });
}
presets.sort((a, b) => (ORDER.indexOf(a.id) + 1 || 99) - (ORDER.indexOf(b.id) + 1 || 99));

const body = presets
  .map(
    (p) =>
      `  {\n    id: ${JSON.stringify(p.id)},\n    name: ${JSON.stringify(p.name)},\n    scheme: ${JSON.stringify(p.scheme)},\n    tokens: {\n${TOKENS.map((t) => `      ${JSON.stringify(t)}: ${JSON.stringify(p.tokens[t])},`).join("\n")}\n    },\n  },`,
  )
  .join("\n");
writeFileSync(
  out,
  `// Generated by scripts/gen-presets.ts from desktop/design/presets/*.css. Do not edit.
export const TOKEN_NAMES = ${JSON.stringify(TOKENS)} as const;
export type TokenName = (typeof TOKEN_NAMES)[number];
export type Tokens = Record<TokenName, string>;
export interface Preset {
  id: string;
  name: string;
  scheme: "dark" | "light";
  tokens: Tokens;
}
export const PRESETS: readonly Preset[] = [
${body}
];
export const PRESET_IDS: readonly string[] = PRESETS.map((p) => p.id);
`,
);
console.log(`${presets.length} presets -> src/theme/presets.ts`);
