#!/usr/bin/env node
// Copies the parts of desktop/design the app ships verbatim into src/design.
// The design directory stays the source; re-run after it changes:
//   pnpm sync-design
import { cpSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const design = resolve(here, "..", "design");
const out = resolve(here, "..", "src", "design");
mkdirSync(join(out, "fonts"), { recursive: true });
mkdirSync(join(out, "presets"), { recursive: true });
for (const f of ["base.css", "tokens.css"]) cpSync(join(design, f), join(out, f));
for (const f of ["Geist-Variable.woff2", "InterVariable.woff2", "JetBrainsMono-Variable.woff2", "LICENSES.md"]) {
  cpSync(join(design, "fonts", f), join(out, "fonts", f));
}
cpSync(join(design, "presets", "dark.css"), join(out, "presets", "dark.css"));
cpSync(join(design, "icons", "sprite.js"), join(out, "sprite.js"));
cpSync(join(design, "icons", "LICENSE.md"), join(out, "ICONS-LICENSE.md"));
// The icon names the sprite defines, for the typed Icon component.
const names = JSON.parse(readFileSync(join(out, "sprite.js"), "utf8").match(/window\.PH_ICONS=(\[[^\]]*\])/)[1]);
writeFileSync(
  join(out, "icon-names.ts"),
  `// Generated by scripts/sync-design.mjs from icons/sprite.js. Do not edit.\nexport const ICON_NAMES = ${JSON.stringify(names.map((n) => n.replace(/^ph-/, "")))} as const;\nexport type IconName = (typeof ICON_NAMES)[number];\n`,
);
console.log(`synced design -> src/design (${names.length} icons)`);
